language: java

addons:
  sonarcloud:
    organization: "cseppento-github"

jdk:
  - oraclejdk8

script:
  - ./gradlew build sonarqube -s --scan

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/
