language: java

addons:
  sonarcloud:
    organization: "cseppento-github"

jdk:
  - oraclejdk8

script:
  # check that test-projects are valid before building the plugin
  - cd test-projects && ../gradlew build -s
  - ./gradlew build sonarqube -s --scan

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/
