language: java

addons:
  sonarcloud:
    organization: "cseppento-github"

jdk:
  - oraclejdk8

script:
  # check that test-projects are valid before building the plugin
  - ./gradlew --info --stacktrace --project-dir test-projects build
  - ./gradlew --info --stacktrace --scan build sonarqube

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/
