/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 02 14:05:21 GMT 2017
 */

package com.github.cseppento.gradle.evosuite.testprojects.simple;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut;
import java.util.SortedSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleObjectSut_ESTest extends SimpleObjectSut_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(1L);
      simpleObjectSut0.guessDivisor(1L);
      simpleObjectSut0.check();
      assertEquals(1L, simpleObjectSut0.getValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(0L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid divisor: 0
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut((-164L));
      long long0 = simpleObjectSut0.getValue();
      assertEquals(164L, long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      simpleObjectSut0.check();
      assertEquals(0L, simpleObjectSut0.getValue());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(1173L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(162L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 162 is not a divisor of 1173
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(1L);
      simpleObjectSut0.guessDivisor(1L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(1L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 1 is already added as a divisor of 1
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut((-1L));
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor((-1L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid divisor: -1
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      simpleObjectSut0.guessDivisor(2350L);
      simpleObjectSut0.check();
      assertEquals(0L, simpleObjectSut0.getValue());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      SortedSet<Long> sortedSet0 = simpleObjectSut0.getDivisors();
      assertTrue(sortedSet0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(1915L);
      String string0 = simpleObjectSut0.toString();
      assertEquals("SimpleObjectSut of 1915 with divisors []", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      long long0 = simpleObjectSut0.getValue();
      assertEquals(0L, long0);
  }
}
