/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 02 14:08:59 GMT 2017
 */

package com.github.cseppento.gradle.evosuite.testprojects.duckduckgo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.cseppento.gradle.evosuite.testprojects.duckduckgo.DuckDuckGoApp;
import com.github.cseppento.gradle.evosuite.testprojects.duckduckgo.DuckDuckGoClient;
import java.io.ByteArrayInputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DuckDuckGoApp_ESTest extends DuckDuckGoApp_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[18];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, (byte)0, 3688);
      MockPrintStream mockPrintStream0 = new MockPrintStream("C^&x\"G5~.fU");
      DuckDuckGoApp duckDuckGoApp0 = new DuckDuckGoApp(byteArrayInputStream0, mockPrintStream0, (DuckDuckGoClient) null);
      duckDuckGoApp0.run();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("= <k5{3K1,)U]?*V)G3");
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream("= <k5{3K1,)U]?*V)G3");
      DuckDuckGoApp duckDuckGoApp0 = new DuckDuckGoApp(mockFileInputStream0, mockPrintStream0, (DuckDuckGoClient) null);
      // Undeclared exception!
      try { 
        duckDuckGoApp0.run();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failure!
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.duckduckgo.DuckDuckGoApp", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        DuckDuckGoApp.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/http/client/methods/HttpUriRequest
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.duckduckgo.DuckDuckGoApp", e);
      }
  }
}
