/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 02 14:09:16 GMT 2017
 */

package com.github.cseppento.gradle.evosuite.testprojects.duckduckgo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.cseppento.gradle.evosuite.testprojects.duckduckgo.DuckDuckGoClientException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DuckDuckGoClientException_ESTest extends DuckDuckGoClientException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      DuckDuckGoClientException duckDuckGoClientException0 = new DuckDuckGoClientException("", mockThrowable0);
  }
}
